### ISSUE TITLE
Allow user to configure not using `O` and `I`

### ISSUE THREAD

**Issue by dousha** [cunzaizhuyi/hashplate-cn#2]
It's more of a cosmetic/conformance thing. 

The current standard for license plates rules out the use of `O` (upper case `o`) and `I` (upper case `i`) in favour of using `0` (zero) and `1` (one) only. Maybe we can add it as an option?

**Comment by cunzaizhuyi** [comment]
Thank you. 
Learned. 
Welcome PR.

**Comment by cunzaizhuyi** [comment]
Removed "I" and "O" in version 1.0.1
